name: 'coco_de_pipeline'
version: '1.0.0'

profile: 'default'

model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"

models:
  coco_de_pipeline:
    silver:
      +schema: SILVER
      +materialized: table
    gold:
      +schema: GOLD
      +materialized: table
