-- ============================================================
-- 08: Data Quality - Data Metric Functions (DMFs)
-- System + Custom DMFs across Bronze / Silver / Gold layers
-- Schedule: 60 MINUTES on all monitored tables
-- ============================================================

-- ============================================================
-- CUSTOM DMFs
-- ============================================================

-- Positive amounts: returns count of rows with negative TOTAL_AMOUNT
CREATE OR REPLACE DATA METRIC FUNCTION COCO_DE_DEMO.PUBLIC.DMF_POSITIVE_AMOUNTS(
  ARG_T TABLE(TOTAL_AMOUNT NUMBER)
)
RETURNS NUMBER
AS
$$
  SELECT COUNT(*) FROM ARG_T
  WHERE TOTAL_AMOUNT < 0
$$;

-- Referential integrity: returns count of orders with no matching customer
CREATE OR REPLACE DATA METRIC FUNCTION COCO_DE_DEMO.PUBLIC.DMF_ORDERS_CUSTOMER_FK(
  ARG_T TABLE(CUSTOMER_ID NUMBER, ORDER_ID NUMBER)
)
RETURNS NUMBER
AS
$$
  SELECT COUNT(*) FROM ARG_T o
  WHERE o.CUSTOMER_ID IS NOT NULL
    AND NOT EXISTS (
      SELECT 1 FROM COCO_DE_DEMO.BRONZE.CUSTOMERS c
      WHERE c.CUSTOMER_ID = o.CUSTOMER_ID
    )
$$;


-- ============================================================
-- BRONZE LAYER: System DMFs
-- ============================================================

-- Orders: full coverage (NULL_COUNT, DUPLICATE_COUNT, ROW_COUNT, FRESHNESS, + custom)
ALTER TABLE COCO_DE_DEMO.BRONZE.ORDERS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (ORDER_ID);
ALTER TABLE COCO_DE_DEMO.BRONZE.ORDERS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (ORDER_ID);
ALTER TABLE COCO_DE_DEMO.BRONZE.ORDERS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();
ALTER TABLE COCO_DE_DEMO.BRONZE.ORDERS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.FRESHNESS ON ();
ALTER TABLE COCO_DE_DEMO.BRONZE.ORDERS
  ADD DATA METRIC FUNCTION COCO_DE_DEMO.PUBLIC.DMF_ORDERS_CUSTOMER_FK ON (CUSTOMER_ID, ORDER_ID);
ALTER TABLE COCO_DE_DEMO.BRONZE.ORDERS
  ADD DATA METRIC FUNCTION COCO_DE_DEMO.PUBLIC.DMF_POSITIVE_AMOUNTS ON (TOTAL_AMOUNT);

-- Customers: NULL_COUNT, DUPLICATE_COUNT, ROW_COUNT, FRESHNESS
ALTER TABLE COCO_DE_DEMO.BRONZE.CUSTOMERS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (EMAIL);
ALTER TABLE COCO_DE_DEMO.BRONZE.CUSTOMERS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (CUSTOMER_ID);
ALTER TABLE COCO_DE_DEMO.BRONZE.CUSTOMERS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();
ALTER TABLE COCO_DE_DEMO.BRONZE.CUSTOMERS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.FRESHNESS ON ();

-- Products: NULL_COUNT, DUPLICATE_COUNT, ROW_COUNT
ALTER TABLE COCO_DE_DEMO.BRONZE.PRODUCTS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (PRODUCT_ID);
ALTER TABLE COCO_DE_DEMO.BRONZE.PRODUCTS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (PRODUCT_ID);
ALTER TABLE COCO_DE_DEMO.BRONZE.PRODUCTS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();

-- Order Items: NULL_COUNT on order_id FK
ALTER TABLE COCO_DE_DEMO.BRONZE.ORDER_ITEMS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (ORDER_ID);

-- Payments: NULL_COUNT on order_id FK
ALTER TABLE COCO_DE_DEMO.BRONZE.PAYMENTS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (ORDER_ID);

-- Shipments: NULL_COUNT on order_id FK
ALTER TABLE COCO_DE_DEMO.BRONZE.SHIPMENTS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (ORDER_ID);


-- ============================================================
-- SILVER LAYER: System + Custom DMFs
-- ============================================================

ALTER TABLE COCO_DE_DEMO.SILVER.STG_ORDERS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (ORDER_ID);
ALTER TABLE COCO_DE_DEMO.SILVER.STG_ORDERS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (ORDER_ID);
ALTER TABLE COCO_DE_DEMO.SILVER.STG_ORDERS
  ADD DATA METRIC FUNCTION COCO_DE_DEMO.PUBLIC.DMF_POSITIVE_AMOUNTS ON (TOTAL_AMOUNT);

ALTER TABLE COCO_DE_DEMO.SILVER.STG_CUSTOMERS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (CUSTOMER_ID);


-- ============================================================
-- GOLD LAYER: System DMFs
-- ============================================================

ALTER TABLE COCO_DE_DEMO.GOLD.FACT_SALES
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (ORDER_ID);
ALTER TABLE COCO_DE_DEMO.GOLD.FACT_SALES
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (ORDER_ID);
ALTER TABLE COCO_DE_DEMO.GOLD.FACT_SALES
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();

ALTER TABLE COCO_DE_DEMO.GOLD.DIM_CUSTOMERS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();

ALTER TABLE COCO_DE_DEMO.GOLD.DIM_PRODUCTS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();

ALTER TABLE COCO_DE_DEMO.GOLD.DIM_DATES
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (DATE_KEY);
ALTER TABLE COCO_DE_DEMO.GOLD.DIM_DATES
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (DATE_KEY);
ALTER TABLE COCO_DE_DEMO.GOLD.DIM_DATES
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();

ALTER TABLE COCO_DE_DEMO.GOLD.FACT_SHIPMENT_PERFORMANCE
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (SHIPMENT_ID);
ALTER TABLE COCO_DE_DEMO.GOLD.FACT_SHIPMENT_PERFORMANCE
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (SHIPMENT_ID);
ALTER TABLE COCO_DE_DEMO.GOLD.FACT_SHIPMENT_PERFORMANCE
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();

ALTER TABLE COCO_DE_DEMO.GOLD.FACT_PAYMENT_SUMMARY
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (ORDER_ID);
ALTER TABLE COCO_DE_DEMO.GOLD.FACT_PAYMENT_SUMMARY
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (ORDER_ID);
ALTER TABLE COCO_DE_DEMO.GOLD.FACT_PAYMENT_SUMMARY
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();

ALTER TABLE COCO_DE_DEMO.GOLD.FACT_DAILY_REVENUE
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (REVENUE_DATE);
ALTER TABLE COCO_DE_DEMO.GOLD.FACT_DAILY_REVENUE
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (REVENUE_DATE);
ALTER TABLE COCO_DE_DEMO.GOLD.FACT_DAILY_REVENUE
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();


-- ============================================================
-- EVALUATION SCHEDULES: 60 minutes on all monitored tables
-- ============================================================

-- Bronze
ALTER TABLE COCO_DE_DEMO.BRONZE.ORDERS      SET DATA_METRIC_SCHEDULE = '60 MINUTES';
ALTER TABLE COCO_DE_DEMO.BRONZE.CUSTOMERS    SET DATA_METRIC_SCHEDULE = '60 MINUTES';
ALTER TABLE COCO_DE_DEMO.BRONZE.PRODUCTS     SET DATA_METRIC_SCHEDULE = '60 MINUTES';
ALTER TABLE COCO_DE_DEMO.BRONZE.ORDER_ITEMS  SET DATA_METRIC_SCHEDULE = '60 MINUTES';
ALTER TABLE COCO_DE_DEMO.BRONZE.PAYMENTS     SET DATA_METRIC_SCHEDULE = '60 MINUTES';
ALTER TABLE COCO_DE_DEMO.BRONZE.SHIPMENTS    SET DATA_METRIC_SCHEDULE = '60 MINUTES';

-- Silver
ALTER TABLE COCO_DE_DEMO.SILVER.STG_ORDERS    SET DATA_METRIC_SCHEDULE = '60 MINUTES';
ALTER TABLE COCO_DE_DEMO.SILVER.STG_CUSTOMERS  SET DATA_METRIC_SCHEDULE = '60 MINUTES';

-- Gold
ALTER TABLE COCO_DE_DEMO.GOLD.FACT_SALES     SET DATA_METRIC_SCHEDULE = '60 MINUTES';
ALTER TABLE COCO_DE_DEMO.GOLD.DIM_CUSTOMERS  SET DATA_METRIC_SCHEDULE = '60 MINUTES';
ALTER TABLE COCO_DE_DEMO.GOLD.DIM_PRODUCTS   SET DATA_METRIC_SCHEDULE = '60 MINUTES';
ALTER TABLE COCO_DE_DEMO.GOLD.DIM_DATES      SET DATA_METRIC_SCHEDULE = '60 MINUTES';
ALTER TABLE COCO_DE_DEMO.GOLD.FACT_SHIPMENT_PERFORMANCE SET DATA_METRIC_SCHEDULE = '60 MINUTES';
ALTER TABLE COCO_DE_DEMO.GOLD.FACT_PAYMENT_SUMMARY      SET DATA_METRIC_SCHEDULE = '60 MINUTES';
ALTER TABLE COCO_DE_DEMO.GOLD.FACT_DAILY_REVENUE         SET DATA_METRIC_SCHEDULE = '60 MINUTES';
